### ISSUE TITLE
ESP connection to Board 

### ISSUE THREAD

**Issue by pedrware** [edenhaus/esphome-extraflame#1]
Hi,

Can you show how ESP connects to the board?

Please

**Comment by edenhaus** [comment]
Hi, I'm busy this week, but I will provide you hopefully with some information by the end of next week.

I will also update the component to meet the new "external component" structure introduced in 1.18, which makes it a lot easier to use this component

**Comment by pedrware** [comment]
Do you have any news?

**Comment by edenhaus** [comment]
Sorry it's summer and I totally forgotten this issue.
My oven is switched off and I will active it in September. Until there you need to use the current installation in the readme file.
Probably by the end of september I will be switching to the new "external component" way

**Comment by edenhaus** [comment]
I totally misunderstood your question. I will add some details soon. I will starting to prepare my oven for the winter in the next weeks
