### ISSUE TITLE
Hex traduction for micro nova n100

### ISSUE THREAD

**Issue by NeOdYmS** [edenhaus/esphome-extraflame#3]
I found this 

https://github.com/cotestatnt/PelletStoveMicronova

It's in Italian but a lot of reading information for the stove

**Comment by edenhaus** [comment]
Hi, my board is not a micronova n100 or at least it's not written on it.
The hardest part is to find out, where the values are stored. The values I found on Internet are not working for me.
So you need to do it your helf. I know the dump functionality can be improved but currently I'm short on time. Also this code is my first code in c++.

**Comment by edenhaus** [comment]
I have added my analysis under `/docs/hex address translation.md`
